### Recuperar todas las peliculas
GET http://localhost:38312/movies

### Recuperar una pelicula por id
GET  http://localhost:38312/movies/9c52903b-720e-11ef-92a4-d8bbc14f718d

### Recupera todas las peliculas por un genero
GET http://localhost:38312/movies?genre=Crime

### Crear una pelicula con POST
POST http://localhost:38312/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,

    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ]
}

### Borrar una pelicula
DELETE http://localhost:38312/movies/9962fabd-746c-11ef-86cf-a2aafb79dea2

### Para actualizar una pelicula
PATCH http://localhost:38312/movies/4c9079a4-7469-11ef-86cf-a2aafb79dea2
Content-Type: application/json

{
  "year": 2024,
  "director": "Quentin Tarantililo"
}